### ISSUE TITLE
Failed opening required 'Console/CommandLine.php'

### ISSUE THREAD

**Issue by kevinvanrijn** [cweiske/php-sqllint#11]
After setting up php-sqllint with:

	composer global require 'cweiske/php-sqllint=*'
	sudo ln -s ~/.composer/vendor/bin/php-sqllint /usr/local/bin/php-sqllint

Running `php-sqllint /var/www/path/to/file/db.sql` produces:

	PHP Warning:  require_once(Console/CommandLine.php): failed to open stream: 
	No such file or directory in /home/someguy/.composer/vendor/cweiske/php-sqll
	int/src/phpsqllint/Cli.php on line 16
	PHP Fatal error:  require_once(): Failed opening required 'Console/CommandLi
	ne.php' (include_path='.:/usr/share/php:/usr/share/pear:/home/someguy/.compo
	ser/vendor/cweiske/php-sqllint/src/phpsqllint/../') in /home/someguy/.compos
	er/vendor/cweiske/php-sqllint/src/phpsqllint/Cli.php on line 16

**Comment by kevinvanrijn** [comment]
Okay, after updating with `composer global update` I magically found this working. Apparently it only works when it's being run from the `.composer/` directory.

I'm guessing the PHP is trying to find `CommandLine.php` in a directory relative to the current directory rather then its own path?

---

So, a workaround for my usecase. I changed:

    find . -type f -name '*.sql' -not -path "./vendor/*" -exec php-sqllint '{}' ';'

to

    prevdir=$(pwd)
    cd ~/.composer/
    find "${prevdir}" -type f -name '*.sql' -not -path "${prevdir}/vendor/*" -exec php-sqllint '{}' ';'
    cd "${prevdir}"

Making it work "correctly".

---

And since I haven't mentioned it I'm using version 0.1.3.

	$ php-sqllint --version
	/usr/local/bin/php-sqllint version 0.1.3.

**Comment by cweiske** [comment]
I never tried to require `php-sqllint` via composer and run it there from the vendor/bin directory. The only way I meant to have it executed is via the phar file, or from a checkout with `./bin/php-sqllint ...`.

I know what's going on: It tries to include `vendor/autoload.php`, which is relative to the current dir, instead of using `__DIR__ . "/../vendor/autoload.php"` first - so it uses your project's autoloader, not its own one.
